# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20160818_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='play_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
